---
title: Guangchuang's repo for R packages
author: "\\

	Guangchuang Yu\\

        School of Public Health, The University of Hong Kong"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

I have developed **3** packages on `CRAN` and **7** on `Bioconductor`. For `CRAN` packages, you can use `install.packages()` to install them directly and for `Bioconductor` packages, you need to follow the guide on package homepage by using `biocLite()` to install.

If you are interesting, please visit their homepage to learn more.

+ CRAN
	- [dlstats](http://cran.r-project.org/package=dlstats): `r ypages:::packageTitle('dlstats', 'CRAN')`
	- [emojifont](http://cran.r-project.org/package=emojifont): `r ypages:::packageTitle('emojifont', 'CRAN')`
	- [rvcheck](http://cran.r-project.org/package=rvcheck): `r ypages:::packageTitle('rvcheck', 'CRAN')`
+ Bioconductor
	- [ChIPseeker](https://guangchuangyu.github.io/ChIPseeker): `r ypages:::packageTitle('ChIPseeker', 'BioC')`
	- [clusterProfiler](https://guangchuangyu.github.io/clusterProfiler): `r ypages:::packageTitle('clusterProfiler', 'BioC')`
	- [DOSE](https://guangchuangyu.github.io/DOSE): `r ypages:::packageTitle('DOSE', 'BioC')`
	- [ggtree](https://guangchuangyu.github.io/ggtree): `r ypages:::packageTitle('ggtree', 'BioC')`
	- [GOSemSim](https://guangchuangyu.github.io/GOSemSim): `r ypages:::packageTitle('GOSemSim', 'BioC')`
	- [meshes](https://guangchuangyu.github.io/meshes): `r ypages:::packageTitle('meshes', 'BioC')`
	- [ReactomePA](https://guangchuangyu.github.io/ReactomePA): `r ypages:::packageTitle('ReactomePA', 'BioC')`


--------------------------------------------------------------------------------------------------

This repo is mainly for my `R` packages that only hosted on `github`.

```{r echo=FALSE}
bindir <- max(list.files('bin/windows/contrib', full.names=T))
srcdir <- 'src/contrib'
source("../get_file.R")
```

```r
repo = c("https://cran.rstudio.com",
         "https://bioconductor.org/packages/release/bioc",
         "https://guangchuangyu.github.io/drat")
```


## [chinamap](https://github.com/GuangchuangYu/chinamap)

```r
install.packages("scatterpie", repo=repo)
```

- vignette: [China Map](https://guangchuangyu.github.io/chinamap/)
- windows binary: `r get_file(bindir, 'chinamap')`
- package source: `r get_file(srcdir, 'chinamap')`



## [scatterpie](https://github.com/GuangchuangYu/scatterpie)

```r
install.packages("scatterpie", repo=repo)
```

- vignette: [scatter pie plot](https://guangchuangyu.github.io/scatterpie/)
- windows binary: `r get_file(bindir, 'scatterpie')`
- package source: `r get_file(srcdir, 'scatterpie')`


## [seqcombo](https://github.com/GuangchuangYu/seqcombo)

```r
install.packages("seqcombo", repo=repo)
```

- vignette: [sequence recombination visualization](https://guangchuangyu.github.io/seqcombo/)
- windows binary: `r get_file(bindir, 'seqcombo')`
- package source: `r get_file(srcdir, 'seqcombo')`

## [seqmagick](https://github.com/GuangchuangYu/seqmagick)

```r
install.packages("seqmagick", repo=repo)
```

- vignette: [sequence manipulation](https://guangchuangyu.github.io/seqmagick/)
- windows binary: `r get_file(bindir, 'seqmagick')`
- package source: `r get_file(srcdir, 'seqmagick')`


<!--

## [skleid](https://github.com/GuangchuangYu/skleid)

```r
install.packages("skleid", repo=repo)
```

- windows binary: `r get_file(bindir, 'skleid')`
- package source: `r get_file(srcdir, 'skleid')`

-->
